py_test_local: # Run tests without the need to install first
	python3 setup.py pytest --addopts --ignore=tests/accept
py_test_accept:
	python3 setup.py pytest --addopts tests/accept
py_test:
	pytest -s

py_install:
	python3 setup.py install

py_build:
	python3 setup.py build


