source 'https://rubygems.org'

gemspec

# General dependencies
gem 'json', '~> 2.7'
gem 'rake', '~> 13.2'

# Test dependencies
group :test do
  gem 'rspec', '~> 3.10'
  gem "rspec-json_expectations", "~> 2.2"
  gem 'webmock', '~> 3.23'
  gem 'simplecov', '~> 0.22'
  gem 'codecov', require: false
end

# Development and test dependencies
group :development, :test do
  gem 'pry', '~> 0.14'
end
